<a href="https://colab.research.google.com/github/smitp2705/Sup_PR5/blob/main/PR5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part A: Ensemble Learning & Conceptual Foundation (Theory)

## Q1. What is Ensemble Learning?

**Answer:**

Ensemble Learning is a machine learning technique in which multiple machine learning models are combined to build a stronger and more accurate predictive model. Instead of relying on a single model, ensemble learning aggregates the predictions of several base models to improve prediction accuracy, reduce errors, and increase model robustness.

The main objective of ensemble learning is to combine the strengths of individual models while minimizing their weaknesses.

**Example:** Random Forest is an ensemble of multiple Decision Trees.

---

## Q2. Explain Bagging and Boosting. What is their importance in Machine Learning?

**Answer:**

### Bagging (Bootstrap Aggregating)

Bagging is an ensemble learning technique where multiple models are trained independently using different bootstrap samples of the training dataset. The final prediction is obtained using majority voting for classification or averaging for regression.

### Boosting

Boosting is an ensemble learning technique in which models are trained sequentially. Each new model attempts to correct the mistakes made by the previous model, resulting in improved predictive performance.

### Importance

* Improves prediction accuracy.
* Reduces overfitting.
* Reduces bias and variance.
* Produces stable and robust models.
* Widely used in classification and regression problems.
* Performs well on large and complex datasets.

---

## Q3. What are the advantages of Ensemble Learning?

**Answer:**

Ensemble Learning offers several advantages over individual machine learning models.

### Advantages

* Higher prediction accuracy.
* Better generalization on unseen data.
* Reduces overfitting.
* Produces stable models.
* Handles noisy datasets effectively.
* Improves reliability.
* Works for both classification and regression tasks.
* Suitable for real-world predictive applications.

---

## Q4. Explain the working principle of:

### a) Bagging

**Answer:**

Bagging creates multiple bootstrap samples from the original dataset. A separate model is trained on each sample independently. Their predictions are then combined using majority voting for classification or averaging for regression.

---

### b) AdaBoost

**Answer:**

AdaBoost (Adaptive Boosting) trains weak learners sequentially. After every iteration, incorrectly classified samples receive higher weights so that the next learner focuses more on difficult observations.

---

### c) Gradient Boosting

**Answer:**

Gradient Boosting builds models sequentially by minimizing prediction errors. Each new model learns the residual errors produced by the previous model using gradient descent optimization.

---

### d) XGBoost

**Answer:**

XGBoost (Extreme Gradient Boosting) is an optimized implementation of Gradient Boosting. It includes regularization, tree pruning, parallel processing, and efficient handling of missing values, making it faster and more accurate.

---

### e) LightGBM

**Answer:**

LightGBM is a gradient boosting framework developed by Microsoft. It uses histogram-based learning and leaf-wise tree growth to achieve high speed and excellent predictive performance, especially on large datasets.

---

### f) Voting Ensemble

**Answer:**

Voting combines predictions from multiple machine learning models.

* **Hard Voting:** The final prediction is based on majority voting.
* **Soft Voting:** The final prediction is based on the average probability predicted by all models.

---

### g) Stacking Ensemble

**Answer:**

Stacking combines predictions from multiple base learners and uses another machine learning model called a meta-learner to produce the final prediction.

---

## Q5. Explain the applications of Ensemble Learning.

**Answer:**

Ensemble Learning is widely used in various real-world applications because of its high predictive accuracy and robustness.

### Applications

* Fraud Detection
* Credit Risk Assessment
* Medical Diagnosis
* Disease Prediction
* Customer Churn Prediction
* Loan Approval Prediction
* Stock Market Forecasting
* Weather Forecasting
* Recommendation Systems
* Spam Email Detection
* Predictive Maintenance
* Sales Forecasting
* Insurance Claim Prediction
* Cybersecurity
* Autonomous Vehicles


---

# Conclusion

In this section, the fundamental concepts of Ensemble Learning were studied. Bagging, Boosting, Voting, and Stacking are powerful ensemble techniques that combine multiple machine learning models to improve prediction accuracy, reduce bias and variance, and increase model stability. These techniques are widely used in both classification and regression problems and form the foundation of modern predictive analytics. Understanding these concepts is essential before implementing ensemble models on the Smart Outcome Predictor dataset.

# Part B: Dataset Understanding & Preparation

In [10]:

# Import Required Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.tree import (
    DecisionTreeClassifier,
    DecisionTreeRegressor
)

from sklearn.ensemble import (
    BaggingClassifier,
    BaggingRegressor,
    AdaBoostClassifier,
    AdaBoostRegressor,
    GradientBoostingClassifier,
    GradientBoostingRegressor)
from lightgbm import (
    LGBMClassifier,
    LGBMRegressor)
from xgboost import (
    XGBClassifier,
    XGBRegressor)
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import warnings
warnings.filterwarnings("ignore")

### Interpretation

The required libraries are imported for data handling, preprocessing, encoding, scaling, and train-test splitting.

In [11]:
df = pd.read_csv("/content/Smart_Outcome_Predictor_Dataset_5200.csv")

df.head()

,student_id,age,country_region,device_type,education_background,course_level,course_category,course_start_date,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
0,700001,32,Europe,Laptop,Undergrad,Intermediate,Business,2024-03-18,12,1,7.6,1,6,1,1,53.3,0.655,0,49.8
1,700002,17,Europe,Laptop,Undergrad,Intermediate,Programming,2024-08-22,34,16,27.2,6,4,7,1,51.5,1.000,1,84.0
2,700003,25,Europe,Mobile,Graduate,Advanced,Programming,2024-09-28,39,6,7.1,16,2,2,0,62.2,0.810,0,62.5
3,700004,26,Asia,Mobile,Undergrad,Beginner,Design,2024-03-09,10,34,22.1,57,9,6,0,59.3,0.875,1,89.5
4,700005,26,Asia,Tablet,WorkingPro,Advanced,Business,2024-03-21,12,22,32.3,41,9,2,0,65.1,0.814,0,67.4

### Interpretation

The dataset has been loaded successfully. The first five records help us understand the available features.

In [12]:
print("Rows, Columns :", df.shape)
df.info()

Rows, Columns : (5200, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             5200 non-null   int64
 1   age                    5200 non-null   int64
 2   country_region         5200 non-null   object
 3   device_type            5200 non-null   object
 4   education_background   5200 non-null   object
 5   course_level           5200 non-null   object
 6   course_category        5200 non-null   object
 7   course_start_date      5200 non-null   object
 8   week_of_year           5200 non-null   int64
 9   sessions               5200 non-null   int64
 10  time_spent_hours       5088 non-null   float64
 11  videos_watched         5200 non-null   int64
 12  quiz_attempts          5200 non-null   int64
 13  assignments_submitted  5200 non-null   int64
 14  forum_posts            5200 non-null   int64
 15  avg_quiz_score         5119 non-null   float64
 16  attendance_rate        5120 non-null   float64
 17  completion_status      5200 non-null   int64
 18  final_score            5200 non-null   float64
dtypes: float64(4), int64(9), object(6)
memory usage: 772.0+ KB

### Interpretation

This shows the data types and verifies whether any column contains missing values.

In [13]:
df.describe()

,student_id,age,week_of_year,sessions,time_spent_hours,videos_watched,quiz_attempts,assignments_submitted,forum_posts,avg_quiz_score,attendance_rate,completion_status,final_score
count,5200.000000,5200.000000,5200.000000,5200.000000,5088.000000,5200.000000,5200.000000,5200.000000,5200.000000,5119.000000,5120.000000,5200.000000,5200.000000
mean,702600.500000,24.339615,26.621538,19.121923,18.216156,25.852885,6.995769,3.835769,1.585577,66.842626,0.847189,0.375385,74.821615
std,1501.255031,5.578864,15.007731,10.726708,10.734114,17.720493,2.568017,1.951802,1.270640,13.813992,0.113545,0.484269,13.531829
min,700001.000000,16.000000,1.000000,1.000000,0.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.313000,0.000000,35.200000
25%,701300.750000,20.000000,14.000000,11.000000,10.300000,13.000000,5.000000,2.000000,1.000000,57.500000,0.768750,0.000000,64.700000
50%,702600.500000,24.000000,27.000000,17.000000,16.100000,23.000000,7.000000,4.000000,1.000000,66.900000,0.855000,0.000000,74.100000
75%,703900.250000,28.000000,40.000000,25.000000,23.800000,35.000000,9.000000,5.000000,2.000000,76.200000,0.942000,1.000000,84.900000
max,705200.000000,45.000000,52.000000,94.000000,76.800000,158.000000,20.000000,12.000000,8.000000,100.000000,1.000000,1.000000,100.000000

### Interpretation

The summary provides statistical information such as mean, standard deviation, minimum, maximum, and quartiles for numerical columns.

In [14]:
df.isnull().sum()

student_id                 0
age                        0
country_region             0
device_type                0
education_background       0
course_level               0
course_category            0
course_start_date          0
week_of_year               0
sessions                   0
time_spent_hours         112
videos_watched             0
quiz_attempts              0
assignments_submitted      0
forum_posts                0
avg_quiz_score            81
attendance_rate           80
completion_status          0
final_score                0
dtype: int64

In [15]:
# Numerical columns
num_cols = df.select_dtypes(include=np.number).columns

# Categorical columns
cat_cols = df.select_dtypes(include="object").columns

# Fill missing values
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

### Interpretation

Numerical missing values are replaced with the median, while categorical missing values are replaced with the most frequent value (mode).

In [16]:
df.isnull().sum()

student_id               0
age                      0
country_region           0
device_type              0
education_background     0
course_level             0
course_category          0
course_start_date        0
week_of_year             0
sessions                 0
time_spent_hours         0
videos_watched           0
quiz_attempts            0
assignments_submitted    0
forum_posts              0
avg_quiz_score           0
attendance_rate          0
completion_status        0
final_score              0
dtype: int64

### Interpretation

All missing values have been handled successfully. The dataset is now ready for further preprocessing.

In [17]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

### Remove Non-Predictive Identifier

In [18]:
if "student_id" in df.columns:
    df.drop("student_id", axis=1, inplace=True)

The student_id
 column is a unique identifier assigned to each student. Since it does not represent meaningful behavioral or academic information, it is removed from the predictive feature set.

### Interpretation

Duplicate rows reduce model quality. If the result is zero, the dataset contains no duplicate records.

In [19]:
X = df.drop(["completion_status", "final_score"], axis=1)

y_cls = df["completion_status"]
y_reg = df["final_score"]

### Interpretation

The independent variables are separated from the target variables for both classification and regression tasks.

In [20]:
le = LabelEncoder()

for col in X.select_dtypes(include="object"):
    X[col] = le.fit_transform(X[col])

### Interpretation

Machine learning models require numerical input, so all categorical columns are converted into numeric labels.

In [21]:
scaler = StandardScaler()

X = pd.DataFrame(
    scaler.fit_transform(X),
    columns=X.columns
)

### Interpretation

Standardization scales all numerical features to a similar range, helping many machine learning algorithms perform better.

In [22]:
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X, y_cls,
    test_size=0.2,
    random_state=42,
    stratify=y_cls
)

print(X_train_c.shape, X_test_c.shape)

(4160, 16) (1040, 16)

### Interpretation

The classification dataset is divided into **80% training** and **20% testing** while preserving the class distribution.

In [23]:
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X, y_reg,
    test_size=0.2,
    random_state=42
)

print(X_train_r.shape, X_test_r.shape)

(4160, 16) (1040, 16)

### Interpretation

The regression dataset is divided into training and testing sets for model evaluation on unseen data.

# Part C: Bagging (Bootstrap Aggregating)

Bagging combines predictions from multiple base models trained on different bootstrap samples. It helps reduce variance and improves model stability and accuracy.

In this section, we will:
- Train a base Decision Tree model
- Train a Bagging model
- Compare their performances

In [24]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import BaggingClassifier, BaggingRegressor

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
import numpy as np

### Interpretation

The required models and evaluation metrics are imported for implementing Bagging in both classification and regression tasks.

In [25]:
dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train_c, y_train_c)

pred_dt = dt.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_dt))

Accuracy : 0.6182692307692308

### Interpretation

This is the baseline classifier. Its accuracy will be compared with the Bagging Classifier to measure improvement.

In [26]:
bag_cls = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=42
)

bag_cls.fit(X_train_c, y_train_c)

pred_bag = bag_cls.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_bag))

Accuracy : 0.7144230769230769

### Interpretation

Bagging combines predictions from multiple Decision Trees, reducing overfitting and improving generalization.

In [27]:
print(classification_report(y_test_c, pred_bag))

              precision    recall  f1-score   support

           0       0.75      0.81      0.78       650
           1       0.64      0.55      0.59       390

    accuracy                           0.71      1040
   macro avg       0.69      0.68      0.69      1040
weighted avg       0.71      0.71      0.71      1040

### Interpretation

The report provides Precision, Recall, F1-Score, and Accuracy to evaluate the classification model comprehensively.

In [28]:
dtr = DecisionTreeRegressor(random_state=42)

dtr.fit(X_train_r, y_train_r)

pred_dt = dtr.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_dt))

R2 Score : -0.050031735263256216

### Interpretation

This Decision Tree Regressor serves as the baseline model for comparison with the Bagging Regressor.

In [29]:
bag_reg = BaggingRegressor(
    estimator=DecisionTreeRegressor(),
    n_estimators=100,
    random_state=42
)

bag_reg.fit(X_train_r, y_train_r)

pred_bag = bag_reg.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_bag))

R2 Score : 0.46568291347437685

### Interpretation

Bagging Regressor averages predictions from multiple Decision Trees, resulting in improved prediction accuracy and reduced variance.

In [30]:
print("MAE :", mean_absolute_error(y_test_r, pred_bag))

print("RMSE :", np.sqrt(mean_squared_error(y_test_r, pred_bag)))

print("R2 :", r2_score(y_test_r, pred_bag))

MAE : 8.006259615384618
RMSE : 9.991575013768813
R2 : 0.46568291347437685

### Interpretation

- MAE indicates the average prediction error.
- RMSE penalizes larger prediction errors.
- R² Score shows how well the model explains the variance in the target variable.

In [31]:
comparison = {
    "Model": [
        "Decision Tree Classifier",
        "Bagging Classifier",
        "Decision Tree Regressor",
        "Bagging Regressor"
    ],
    "Score": [
        accuracy_score(y_test_c, dt.predict(X_test_c)),
        accuracy_score(y_test_c, pred_bag if False else bag_cls.predict(X_test_c)),
        r2_score(y_test_r, dtr.predict(X_test_r)),
        r2_score(y_test_r, bag_reg.predict(X_test_r))
    ]
}

pd.DataFrame(comparison)

                      Model     Score
0  Decision Tree Classifier  0.618269
1        Bagging Classifier  0.714423
2   Decision Tree Regressor -0.050032
3         Bagging Regressor  0.465683

### Interpretation

The comparison table summarizes the performance of the base Decision Tree models and their Bagging counterparts.

Generally, Bagging improves performance by reducing variance and making predictions more robust.

# Part D: Boosting Algorithms

Boosting is an ensemble technique where models are trained sequentially.
Each new model tries to correct the errors made by the previous model, leading to better predictive performance.

In this section, we will implement:
- AdaBoost
- Gradient Boosting
- LightGBM
- XGBoost

In [32]:
from sklearn.ensemble import AdaBoostClassifier, AdaBoostRegressor

### Interpretation

AdaBoost combines multiple weak learners into a strong learner by giving higher importance to previously misclassified samples.

In [33]:
ada_cls = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada_cls.fit(X_train_c, y_train_c)

pred_ada = ada_cls.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_ada))

Accuracy : 0.7346153846153847

### Interpretation

The AdaBoost Classifier improves classification performance by sequentially focusing on difficult-to-classify observations.

In [34]:
print(classification_report(y_test_c, pred_ada))

              precision    recall  f1-score   support

           0       0.76      0.84      0.80       650
           1       0.68      0.56      0.61       390

    accuracy                           0.73      1040
   macro avg       0.72      0.70      0.71      1040
weighted avg       0.73      0.73      0.73      1040

### Interpretation

Precision, Recall, F1-Score, and Accuracy indicate the overall classification performance.

In [35]:
ada_reg = AdaBoostRegressor(
    n_estimators=100,
    random_state=42
)

ada_reg.fit(X_train_r, y_train_r)

pred_ada = ada_reg.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_ada))

R2 Score : 0.4091270493383097

### Interpretation

The AdaBoost Regressor improves prediction accuracy by combining multiple weak regression models.

In [36]:
print("MAE :", mean_absolute_error(y_test_r, pred_ada))

print("RMSE :", np.sqrt(mean_squared_error(y_test_r, pred_ada)))

print("R2 :", r2_score(y_test_r, pred_ada))

MAE : 8.556517010018968
RMSE : 10.507066394975183
R2 : 0.4091270493383097

### Interpretation

Lower MAE and RMSE with a higher R² indicate better regression performance.

In [37]:
print("""
AdaBoost Learning Process

Model 1 → Finds Errors
        ↓
Model 2 → Focuses on Previous Errors
        ↓
Model 3 → Focuses on Remaining Errors
        ↓
Final Prediction = Weighted Combination
""")

AdaBoost Learning Process

Model 1 → Finds Errors
        ↓
Model 2 → Focuses on Previous Errors
        ↓
Model 3 → Focuses on Remaining Errors
        ↓
Final Prediction = Weighted Combination

### Interpretation

Unlike Bagging, AdaBoost trains models sequentially, giving higher weight to previously misclassified samples.

In [38]:
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

### Interpretation

Gradient Boosting improves predictions by minimizing the loss function using gradient descent principles.

In [39]:
gb_cls = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb_cls.fit(X_train_c, y_train_c)

pred_gb = gb_cls.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_gb))

Accuracy : 0.7384615384615385

### Interpretation

Gradient Boosting sequentially improves the model by correcting prediction errors from previous trees.

In [40]:
gb_reg = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

gb_reg.fit(X_train_r, y_train_r)

pred_gb = gb_reg.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_gb))

R2 Score : 0.4836848952632389

### Interpretation

Gradient Boosting Regressor minimizes prediction errors by fitting new trees on residual errors.

In [41]:
print("MAE :", mean_absolute_error(y_test_r, pred_gb))

print("RMSE :", np.sqrt(mean_squared_error(y_test_r, pred_gb)))

print("R2 :", r2_score(y_test_r, pred_gb))

MAE : 7.8933619058317195
RMSE : 9.821816982356088
R2 : 0.4836848952632389

### Interpretation

These metrics evaluate the accuracy and error of the regression model.

In [42]:
for lr in [0.01, 0.1, 0.2]:
    model = GradientBoostingClassifier(
        learning_rate=lr,
        random_state=42
    )

    model.fit(X_train_c, y_train_c)

    print(f"LR={lr} :", accuracy_score(y_test_c, model.predict(X_test_c)))

LR=0.01 : 0.6990384615384615
LR=0.1 : 0.7384615384615385
LR=0.2 : 0.7230769230769231

### Interpretation

The learning rate controls how much each tree contributes to the final prediction. A smaller learning rate generally improves generalization but requires more trees.

In [43]:
from lightgbm import LGBMClassifier, LGBMRegressor

### Interpretation

LightGBM is a fast gradient boosting framework designed for high performance and large datasets.

In [44]:
lgb_cls = LGBMClassifier(random_state=42)

lgb_cls.fit(X_train_c, y_train_c)

pred_lgb = lgb_cls.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_lgb))

[LightGBM] [Info] Number of positive: 1562, number of negative: 2598
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001375 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1307
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 16
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.375481 -> initscore=-0.508775
[LightGBM] [Info] Start training from score -0.508775
Accuracy : 0.7192307692307692

### Interpretation

LightGBM uses leaf-wise tree growth, making it faster and often more accurate than traditional boosting methods.

In [45]:
lgb_reg = LGBMRegressor(random_state=42)

lgb_reg.fit(X_train_r, y_train_r)

pred_lgb = lgb_reg.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_lgb))

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006538 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1306
[LightGBM] [Info] Number of data points in the train set: 4160, number of used features: 16
[LightGBM] [Info] Start training from score 74.774183
R2 Score : 0.46189976998204896

### Interpretation

The LightGBM Regressor efficiently predicts continuous values while reducing training time.

In [46]:
print("MAE :", mean_absolute_error(y_test_r, pred_lgb))

print("RMSE :", np.sqrt(mean_squared_error(y_test_r, pred_lgb)))

print("R2 :", r2_score(y_test_r, pred_lgb))

MAE : 8.054539436486785
RMSE : 10.026884468009387
R2 : 0.46189976998204896

### Interpretation

These metrics indicate the predictive performance of the LightGBM Regressor.

In [47]:
from xgboost import XGBClassifier, XGBRegressor

### Interpretation

XGBoost is an optimized gradient boosting algorithm known for high accuracy and regularization capabilities.

In [48]:
xgb_cls = XGBClassifier(
    eval_metric="logloss",
    random_state=42
)

xgb_cls.fit(X_train_c, y_train_c)

pred_xgb = xgb_cls.predict(X_test_c)

print("Accuracy :", accuracy_score(y_test_c, pred_xgb))

Accuracy : 0.7028846153846153

### Interpretation

The XGBoost Classifier improves predictive performance through regularization and efficient tree boosting.

In [49]:
xgb_reg = XGBRegressor(random_state=42)

xgb_reg.fit(X_train_r, y_train_r)

pred_xgb = xgb_reg.predict(X_test_r)

print("R2 Score :", r2_score(y_test_r, pred_xgb))

R2 Score : 0.3716698346205012

### Interpretation

The XGBoost Regressor provides accurate predictions while controlling overfitting using regularization.

In [50]:
print("MAE :", mean_absolute_error(y_test_r, pred_xgb))

print("RMSE :", np.sqrt(mean_squared_error(y_test_r, pred_xgb)))

print("R2 :", r2_score(y_test_r, pred_xgb))

MAE : 8.738472014207106
RMSE : 10.834986565701547
R2 : 0.3716698346205012

### Interpretation

The evaluation metrics help compare XGBoost with the other regression models.

# Part E: Voting & Staking Ensembles

Voting combines predictions from multiple classifiers, while Stacking uses a meta-model to learn from the predictions of base models.

In this section, we implement:
- Voting Classifier
- Hard Voting vs Soft Voting
- Stacking Classifier
- Stacking Regressor

In [51]:
from sklearn.ensemble import VotingClassifier, StackingClassifier, StackingRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression

### Interpretation

Voting and Stacking ensemble methods are imported for combining multiple machine learning models.

In [52]:
hard_vote = VotingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier(random_state=42)),
        ('ada', AdaBoostClassifier(random_state=42)),
        ('gb', GradientBoostingClassifier(random_state=42))
    ],
    voting='hard'
)

hard_vote.fit(X_train_c, y_train_c)

hard_pred = hard_vote.predict(X_test_c)

print("Hard Voting Accuracy:", accuracy_score(y_test_c, hard_pred))

Hard Voting Accuracy: 0.7336538461538461

### Interpretation

Hard Voting predicts the class that receives the majority of votes from all classifiers.

In [53]:
soft_vote = VotingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier(random_state=42)),
        ('ada', AdaBoostClassifier(random_state=42)),
        ('gb', GradientBoostingClassifier(random_state=42))
    ],
    voting='soft'
)

soft_vote.fit(X_train_c, y_train_c)

soft_pred = soft_vote.predict(X_test_c)

print("Soft Voting Accuracy:", accuracy_score(y_test_c, soft_pred))

Soft Voting Accuracy: 0.6461538461538462

### Interpretation

Hard Voting predicts the class that receives the majority of votes from all classifiers.

In [54]:
soft_vote = VotingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier(random_state=42)),
        ('ada', AdaBoostClassifier(random_state=42)),
        ('gb', GradientBoostingClassifier(random_state=42))
    ],
    voting='soft'
)

soft_vote.fit(X_train_c, y_train_c)

soft_pred = soft_vote.predict(X_test_c)

print("Soft Voting Accuracy:", accuracy_score(y_test_c, soft_pred))

Soft Voting Accuracy: 0.6461538461538462

### Interpretation

Soft Voting averages class probabilities from all classifiers and predicts the class with the highest probability.

In [55]:
pd.DataFrame({
    "Voting":["Hard","Soft"],
    "Accuracy":[
        accuracy_score(y_test_c, hard_pred),
        accuracy_score(y_test_c, soft_pred)
    ]
})

  Voting  Accuracy
0   Hard  0.733654
1   Soft  0.646154

### Interpretation

The comparison shows which voting strategy performs better on the dataset.

In [56]:
stack_cls = StackingClassifier(
    estimators=[
        ('dt', DecisionTreeClassifier(random_state=42)),
        ('ada', AdaBoostClassifier(random_state=42)),
        ('gb', GradientBoostingClassifier(random_state=42))
    ],
    final_estimator=LogisticRegression()
)

stack_cls.fit(X_train_c, y_train_c)

stack_pred = stack_cls.predict(X_test_c)

print("Stacking Accuracy:", accuracy_score(y_test_c, stack_pred))

Stacking Accuracy: 0.7403846153846154

### Interpretation

The Stacking Classifier combines predictions from multiple base models using Logistic Regression as the meta-model.

In [57]:
stack_reg = StackingRegressor(
    estimators=[
        ('dt', DecisionTreeRegressor(random_state=42)),
        ('ada', AdaBoostRegressor(random_state=42)),
        ('gb', GradientBoostingRegressor(random_state=42))
    ],
    final_estimator=LinearRegression()
)

stack_reg.fit(X_train_r, y_train_r)

stack_pred = stack_reg.predict(X_test_r)

print("R2 Score:", r2_score(y_test_r, stack_pred))

R2 Score: 0.4850017272791952

### Interpretation

The Stacking Regressor combines multiple regression models and uses Linear Regression as the final estimator.

In [58]:
print("MAE :", mean_absolute_error(y_test_r, stack_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test_r, stack_pred)))
print("R2 :", r2_score(y_test_r, stack_pred))

MAE : 7.88520121167735
RMSE : 9.80928399607937
R2 : 0.4850017272791952

### Interpretation

These metrics evaluate the prediction accuracy of the Stacking Regressor.

# Part F: Model Evaluation & Comparison

This section evaluates all ensemble models using standard classification and regression metrics and identifies the best-performing model.

In [59]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

### Interpretation

The required evaluation metrics are imported for assessing model performance.

In [60]:
models = {
    "Bagging": bag_cls,
    "AdaBoost": ada_cls,
    "Gradient Boosting": gb_cls,
    "LightGBM": lgb_cls,
    "XGBoost": xgb_cls,
    "Stacking": stack_cls
}

cls_result = []

for name, model in models.items():
    pred = model.predict(X_test_c)

    cls_result.append([
        name,
        accuracy_score(y_test_c, pred),
        precision_score(y_test_c, pred),
        recall_score(y_test_c, pred),
        f1_score(y_test_c, pred),
        roc_auc_score(y_test_c, pred)
    ])

cls_result = pd.DataFrame(
    cls_result,
    columns=["Model","Accuracy","Precision","Recall","F1","ROC-AUC"]
)

cls_result

               Model  Accuracy  Precision    Recall        F1   ROC-AUC
0            Bagging  0.714423   0.637982  0.551282  0.591472  0.681795
1           AdaBoost  0.734615   0.677019  0.558974  0.612360  0.699487
2  Gradient Boosting  0.738462   0.677711  0.576923  0.623269  0.706154
3           LightGBM  0.719231   0.644970  0.558974  0.598901  0.687179
4            XGBoost  0.702885   0.616046  0.551282  0.581867  0.672564
5           Stacking  0.740385   0.687500  0.564103  0.619718  0.705128

### Interpretation

The table compares all classification models using Accuracy, Precision, Recall, F1-Score, and ROC-AUC.

In [61]:
reg_models = {
    "Bagging": bag_reg,
    "AdaBoost": ada_reg,
    "Gradient Boosting": gb_reg,
    "LightGBM": lgb_reg,
    "XGBoost": xgb_reg,
    "Stacking": stack_reg
}

reg_result = []

for name, model in reg_models.items():
    pred = model.predict(X_test_r)

    reg_result.append([
        name,
        mean_absolute_error(y_test_r, pred),
        np.sqrt(mean_squared_error(y_test_r, pred)),
        r2_score(y_test_r, pred)
    ])

reg_result = pd.DataFrame(
    reg_result,
    columns=["Model","MAE","RMSE","R2 Score"]
)

reg_result

               Model       MAE       RMSE  R2 Score
0            Bagging  8.006260   9.991575  0.465683
1           AdaBoost  8.556517  10.507066  0.409127
2  Gradient Boosting  7.893362   9.821817  0.483685
3           LightGBM  8.054539  10.026884  0.461900
4            XGBoost  8.738472  10.834987  0.371670
5           Stacking  7.885201   9.809284  0.485002

### Interpretation

The table compares all regression models using MAE, RMSE, and R² Score.

In [62]:
cls_result.sort_values("Accuracy", ascending=False)

               Model  Accuracy  Precision    Recall        F1   ROC-AUC
5           Stacking  0.740385   0.687500  0.564103  0.619718  0.705128
2  Gradient Boosting  0.738462   0.677711  0.576923  0.623269  0.706154
1           AdaBoost  0.734615   0.677019  0.558974  0.612360  0.699487
3           LightGBM  0.719231   0.644970  0.558974  0.598901  0.687179
0            Bagging  0.714423   0.637982  0.551282  0.591472  0.681795
4            XGBoost  0.702885   0.616046  0.551282  0.581867  0.672564

### Interpretation

The model with the highest accuracy is selected as the best classifier.

In [63]:
print("Best Classification Model:")
print(cls_result.loc[cls_result["Accuracy"].idxmax()])

print("\nBest Regression Model:")
print(reg_result.loc[reg_result["R2 Score"].idxmax()])

Best Classification Model:
Model        Stacking
Accuracy     0.740385
Precision      0.6875
Recall       0.564103
F1           0.619718
ROC-AUC      0.705128
Name: 5, dtype: object

Best Regression Model:
Model       Stacking
MAE         7.885201
RMSE        9.809284
R2 Score    0.485002
Name: 5, dtype: object

### Interpretation

The best-performing ensemble models are identified for deployment based on evaluation metrics.

# Part G: Final Analysis & Reporting

In this section, we summarize the performance of all ensemble learning techniques and recommend the best models for deployment.

Finally, we provide business interpretation and project conclusions.

In [64]:
comparison = pd.DataFrame({
    "Technique":["Bagging","Boosting"],
    "Training Style":["Parallel","Sequential"],
    "Main Objective":["Reduce Variance","Reduce Bias"],
    "Advantages":[
        "Less Overfitting, Stable",
        "Higher Accuracy, Better Learning"
    ],
    "Examples":[
        "Bagging",
        "AdaBoost, Gradient Boosting, LightGBM, XGBoost"
    ]
})

comparison

,Technique,Training Style,Main Objective,Advantages,Examples
0,Bagging,Parallel,Reduce Variance,"Less Overfitting, Stable",Bagging
1,Boosting,Sequential,Reduce Bias,"Higher Accuracy, Better Learning","AdaBoost, Gradient Boosting, LightGBM, XGBoost"

### Interpretation

Bagging trains multiple models independently, making it effective in reducing variance and improving stability.

Boosting trains models sequentially, allowing each new model to correct previous mistakes, which generally improves prediction accuracy.

In [65]:
boosting = pd.DataFrame({
    "Algorithm":[
        "AdaBoost",
        "Gradient Boosting",
        "LightGBM",
        "XGBoost"
    ],
    "Strength":[
        "Simple and Effective",
        "High Accuracy",
        "Fast Training",
        "High Accuracy with Regularization"
    ],
    "Limitation":[
        "Sensitive to Noise",
        "Slower Training",
        "Needs Proper Tuning",
        "Higher Computational Cost"
    ]
})

boosting

,Algorithm,Strength,Limitation
0,AdaBoost,Simple and Effective,Sensitive to Noise
1,Gradient Boosting,High Accuracy,Slower Training
2,LightGBM,Fast Training,Needs Proper Tuning
3,XGBoost,High Accuracy with Regularization,Higher Computational Cost

### Interpretation

Each boosting algorithm has different strengths. LightGBM provides faster training, while XGBoost generally offers better prediction accuracy due to regularization.

In [66]:
cls_result.sort_values("Accuracy", ascending=False)

               Model  Accuracy  Precision    Recall        F1   ROC-AUC
5           Stacking  0.740385   0.687500  0.564103  0.619718  0.705128
2  Gradient Boosting  0.738462   0.677711  0.576923  0.623269  0.706154
1           AdaBoost  0.734615   0.677019  0.558974  0.612360  0.699487
3           LightGBM  0.719231   0.644970  0.558974  0.598901  0.687179
0            Bagging  0.714423   0.637982  0.551282  0.591472  0.681795
4            XGBoost  0.702885   0.616046  0.551282  0.581867  0.672564

### Interpretation

The classification models are ranked based on Accuracy. The model with the highest Accuracy is recommended for predicting course completion.

In [67]:
reg_result.sort_values("R2 Score", ascending=False)

               Model       MAE       RMSE  R2 Score
5           Stacking  7.885201   9.809284  0.485002
2  Gradient Boosting  7.893362   9.821817  0.483685
0            Bagging  8.006260   9.991575  0.465683
3           LightGBM  8.054539  10.026884  0.461900
1           AdaBoost  8.556517  10.507066  0.409127
4            XGBoost  8.738472  10.834987  0.371670

### Interpretation

The regression models are ranked based on the R² Score. The model with the highest R² Score is recommended for predicting final student scores.

In [68]:
best_cls = cls_result.loc[cls_result["Accuracy"].idxmax()]

best_cls

Model        Stacking
Accuracy     0.740385
Precision      0.6875
Recall       0.564103
F1           0.619718
ROC-AUC      0.705128
Name: 5, dtype: object

### Interpretation

The above model achieved the highest classification performance and is recommended for deployment.

In [69]:
best_reg = reg_result.loc[reg_result["R2 Score"].idxmax()]

best_reg

Model       Stacking
MAE         7.885201
RMSE        9.809284
R2 Score    0.485002
Name: 5, dtype: object

### Interpretation

The above model achieved the highest regression performance and is recommended for deployment.

In [70]:
print("Recommended Classification Model :", best_cls["Model"])
print("Recommended Regression Model :", best_reg["Model"])

Recommended Classification Model : Stacking
Recommended Regression Model : Stacking

### Interpretation

Based on the evaluation metrics, the selected models provide the most reliable performance and can be used for deployment in predicting course completion and final scores.

## Business Interpretation

* **Early Completion Prediction:** Identify students who are likely or unlikely to successfully complete the course based on their academic performance and engagement patterns.
* **Final Score Estimation:** Predict students' expected final scores before course completion, enabling early assessment of academic outcomes.
* **At-Risk Student Identification:** Detect students who may require additional academic support, mentoring, or personalized guidance.
* **Early Intervention:** Enable institutions and instructors to take timely actions to improve student engagement and reduce the risk of course dropout.
* **Data-Driven Decision Making:** Help instructors and educational institutions make informed decisions based on predictive insights generated by ensemble learning models.
* **Personalized Student Support:** Provide targeted learning resources and interventions according to individual student performance and engagement levels.

# Final Conclusion

This project successfully developed a Smart Outcome Predictor using multiple Ensemble Learning techniques for both classification and regression tasks. The classification task focused on predicting students' course completion status, while the regression task aimed to predict their final academic scores.

Different ensemble techniques, including Bagging, AdaBoost, Gradient Boosting, XGBoost, LightGBM, Voting, and Stacking, were implemented and evaluated. Bagging helped improve model stability by reducing variance, while Boosting algorithms enhanced predictive performance by sequentially learning from previous prediction errors. Voting and Stacking further demonstrated the advantages of combining multiple models to produce more robust and reliable predictions.

The models were systematically compared using classification metrics such as Accuracy, Precision, Recall, F1-Score, and ROC-AUC, along with regression metrics including MAE, RMSE, and R² Score. Based on these evaluation metrics, the best-performing classification and regression models were identified.

From a practical perspective, the developed system can help educational institutions identify students who may be at risk of not completing their courses, estimate expected academic performance, and support early intervention strategies.

Overall, this project demonstrates that Ensemble Learning provides an effective and reliable approach for predicting student outcomes. By leveraging multiple predictive models, the Smart Outcome Predictor can support data-driven decision-making, personalized student assistance, and improved educational outcomes.